name: Feature request
description: Propose an enhancement
title: "feat: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Describe the problem and desired outcome clearly.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What limitation are you facing?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Include API and behavior expectations if relevant.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered

  - type: textarea
    id: impact
    attributes:
      label: Compatibility impact
      description: Mention potential breaking changes.
